version: "3.8"

services:
  es01:
    container_name: my_elasticsearch
    build: .
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
    #   - docker_pirate_elasticsearch_01:/usr/share/elasticsearch/data
    networks:
      - docker_pirate_net
    deploy:
      resources:
        limits:
          memory: 4G

# volumes:
#   docker_pirate_elasticsearch_01:
#     name: docker_pirate_elasticsearch_01


networks:
  docker_pirate_net:
    driver: bridge
    name: docker_pirate_net
