version: "3.8"

services:
  myhelloapp:
    build: .
    environment:
      MONGO_URL: "mongodb://mymongodb:27017/test"
    depends_on:
      - mymongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  mymongodb:
    image: mongo
