version: "3.8"

services:
  flask_app:
    container_name: my_flask_app
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    networks:
      - net_flask_app
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  net_flask_app:
    driver: bridge
    name: net_flask_app
